name: TestCentric.Net462Agent.CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - "*.txt"
      - "*.md"

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  ContinuousIntegration:
    name: Continuous Integration
    runs-on: windows-latest

    env:
        TESTCENTRIC_MYGET_API_KEY: ${{ secrets.TESTCENTRIC_MYGET_API_KEY }}
        TESTCENTRIC_NUGET_API_KEY: ${{ secrets.TESTCENTRIC_NUGET_API_KEY }}
        TESTCENTRIC_CHOCO_API_KEY: ${{ secrets.TESTCENTRIC_CHOCO_API_KEY }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.TESTCENTRIC_GITHUB_ACCESS_TOKEN }}

    steps:
      - name: ⤵️ Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Install dotnet tools
        run: dotnet tool restore

      - name: 🍰 Run cake
        env:
            TESTCENTRIC_MYGET_API_KEY: ${{ secrets.TESTCENTRIC_MYGET_API_KEY }}
            TESTCENTRIC_NUGET_API_KEY: ${{ secrets.TESTCENTRIC_NUGET_API_KEY }}
            TESTCENTRIC_CHOCO_API_KEY: ${{ secrets.TESTCENTRIC_CHOCO_API_KEY }}
            GITHUB_ACCESS_TOKEN: ${{ secrets.TESTCENTRIC_GITHUB_ACCESS_TOKEN }}

        # If you need to get more verbose logging, add the following to the dotnet-cake above:  --verbosity=diagnostic
        run: dotnet cake --target=ContinuousIntegration --configuration=Release

      - name: 🪵 Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Upload Console Logs
          # This path is defined in build-settings.cake
          path: "build-results/*.binlog"
          # if-no-files-found: error

      - name: 🪵 Upload InternalTrace logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: InternalTraceLogs
          # This path is defined in build-settings.cake
          path: "*.log"
          # if-no-files-found: error

      - name: 💾 Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "Test Results"
          path: test-results
